### ISSUE TITLE
ピン留めトゥートを表示するUIをどうにかする

### ISSUE THREAD

**Issue by rinsuki** [cinderella-project/iMast#105]
だいたいトゥート一覧って文脈を知りたかったりして開くものなので、そこで5つくらいドカーンと固定トゥートが表示されてもあんまりうれしくない。

また今のUIは #92 のような不具合も生んでいるので、何かしらいいかんじにしたい。

**Comment by mlny** [comment]
🤔 

![img_0104](https://user-images.githubusercontent.com/5173607/41462054-88ca6354-70cc-11e8-9963-35666ce04a75.PNG)
![img_0105](https://user-images.githubusercontent.com/5173607/41462056-8af9700c-70cc-11e8-9e2b-c69766d244cc.PNG)

(モックアップには実際のスクリーンショットを加工したものを使用しています。問題がありましたらご一報ください)

**Comment by rinsuki** [comment]
とりあえず https://github.com/cinderella-project/iMast/commit/3221b6961d407e10df70330741cf0557ac6f8b93 でピン留めトゥートの文章がやたら長い人対策はできた気がするのでclose
