### ISSUE TITLE
CWつきの投稿に画像が付いていることをTL上に表示する

### ISSUE THREAD

**Issue by mlny** [cinderella-project/iMast#108]
#82 のfixでNSFWの画像がTLにそのまま出なくなったので、それならWebの挙動に合わせたほうがよさそうですが如何でしょうか。

**Comment by rinsuki** [comment]
前からCWの投稿に添付メディアが付いていたらその旨を添えるようにしてるんですが、これじゃだめな感じですか？
![8491d84a-b6c3-457b-bbe6-85230fc90a67](https://user-images.githubusercontent.com/6533808/41884545-e0d1d874-792e-11e8-9075-aaeb240ea2d8.jpeg)

**Comment by mlny** [comment]
一旦投稿詳細画面に行かないと画像が見られないのがアレだと思っていますが、良く考えたらiMastの「1画面内の情報量を増やす」という設計思想にそぐわない気がしてきたので一旦取り下げます。
