### ISSUE TITLE
[iOS12] スクリーンタイムでiMastが「Other」として扱われる

### ISSUE THREAD

**Issue by mlny** [cinderella-project/iMast#109]
本来はSocial Networkingとして扱われるべき

**Comment by rinsuki** [comment]
恐らく、App Storeのジャンル情報かなにかで区別しているので、TestFlight版だとApp Storeから情報を取得できずOther扱いになるのだと思います

**Comment by mlny** [comment]
試しにApp Storeから取得したiMastを使ってみたところSocial Networkingに分類されていました。TestFlight版を使うような人は気にしなさそうなのでCloseします。
