### ISSUE TITLE
プッシュ通知で&gt;等のエンティティがデコードされていない

### ISSUE THREAD

**Issue by unarist** [cinderella-project/iMast#117]
`👨‍⚕️<風邪ですね` という投稿へのお気に入り通知が `👨‍⚕️&lt;風邪ですね` になっている、みたいな話。

**Comment by rinsuki** [comment]
ref: https://github.com/rinsuki/imast-backend/issues/1

**Comment by rinsuki** [comment]
実はプッシュじゃない通知でも同様のバグがある

**Comment by rinsuki** [comment]
2018/09/10 08:56 UTC+09:00 ごろのimast-backendデプロイで修正
