### ISSUE TITLE
長い投稿を通報しようとするとテキストが溢れてる

### ISSUE THREAD

**Issue by unarist** [cinderella-project/iMast#134]
![714f879a-331c-4d3d-b799-cbed09d93bfe](https://user-images.githubusercontent.com/705555/53703951-a0f68500-3e5a-11e9-9858-f0fa4cf254e0.jpeg)
これはまだおとなしい方で、めちゃ長いやつだとめちゃ溢れる。それがリモート投稿だとリモート通報の説明にも重なってくるのでちょっと見た目が…。

**Comment by rinsuki** [comment]
いまのおきもち↓

- placeholderが溢れるのはEurekaのバグ
- それはそれとしてめっちゃ長い文章をそこに突っこむのはどうなのか
- MastodonPostCellで表示してしまえばよい?
    - Eurekaで生のUITableViewCell表示するのどうすんだろね
- とりあえずちょんぎるのが楽
    - とはいえそれもどうなんだ
- とりあえずなんとかはしたいと思っています

**Comment by rinsuki** [comment]
Resolved by brand-new SwiftUI implementation of report screen
