### ISSUE TITLE
3.2 (136) 以降でShareExtensionが動かない

### ISSUE THREAD

**Issue by unarist** [cinderella-project/iMast#138]
最新のベータでShareExtensionが動かなくなりました。メニューからiMastを選ぶと、少しの間固まったり固まらなかったりしたのち、何も表示されません。

3.2 (133) では動き、3.2 (136) や 3.2 (159) で動きませんでした。

iOS12.2

**Comment by rinsuki** [comment]
iPad Air 2 + Safari:

- 数秒フリーズしたあと出てこない
- 数秒フリーズしたあと出てくる
- すっと出てくる

iPhone 8 + Safari:

- すっと出てくる

🤔 🤔 🤔

**Comment by unarist** [comment]
なんかこう、メモリ不足とかそういう話のような気もしてきた（うちは5sで多分確定死）

**Comment by rinsuki** [comment]
iPad Air 2で二つ同時にShare Extensionを開こうとすると再現

**Comment by rinsuki** [comment]
したりしなかったりするしXcodeのデバッガーは最初の起動時しかアタッチしてくれないので完全に謎

**Comment by rinsuki** [comment]
ログ
```
エラー	19:43:57.810276 +0900	iMast	Hub connection error Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named jp.pronama.imast.iMastShare" UserInfo={NSDebugDescription=connection to service named jp.pronama.imast.iMastShare}
デフォルト	19:43:57.811757 +0900	iMast	HOST: Failed to load remote view controller with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named jp.pronama.imast.iMastShare" UserInfo={NSDebugDescription=connection to service named jp.pronama.imast.iMastShare}
デフォルト	19:43:58.249245 +0900	ReportCrash	Formulating report for corpse[6113] iMastShare
```

**Comment by rinsuki** [comment]
メモリ不足で殺されてるっぽいけど、iOSはiOSで20MBで死ぬのはどうなんですかね…という気持ちはあった。別に派手なことしてるわけでもないのに…

**Comment by rinsuki** [comment]
> Memory limits for running app extensions are significantly lower than the memory limits imposed on a foreground app. 

そうですね…
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionCreation.html

**Comment by rinsuki** [comment]
![image](https://user-images.githubusercontent.com/6533808/57493460-f5592d80-72ff-11e9-8e05-3e32433326d8.png)

> WebThread (10): EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=120 MB, unused=0x0)

😢

**Comment by rinsuki** [comment]
どうしようもないので、とりあえず共有プレビューでWebViewをプレビューに使おうとしてコケるのだけ対処する

**Comment by unarist** [comment]
ところでビルド172や175で試したらなんかちゃんと出るようになってました。

**Comment by rinsuki** [comment]
謎だ…

**Comment by rinsuki** [comment]
新共有画面でWebView呼び出しは粉砕されたはずなので、とりあえずこれで様子見ということで
