### ISSUE TITLE
mstdn.jp でストリーミングに繋がらない

### ISSUE THREAD

**Issue by rinsuki** [cinderella-project/iMast#140]

**Comment by kPherox** [comment]
UAを付与しないことが原因でストリーミングが繋がらないことがあります
Whalebirdの例: https://github.com/h3poteto/whalebird-desktop/issues/940#issuecomment-501293611

**Comment by rinsuki** [comment]
https://mstdn.rinsuki.net/@rinsuki/102299499953052018
> $ curl -vH "User-Agent:" https://mstdn.jp
> でCFの403だしそれっぽさ5億
