### ISSUE TITLE
Push 通知を有効化しようとした際に 500 が帰ってくる

### ISSUE THREAD

**Issue by owatan** [cinderella-project/iMast#147]
iMast 本体についての事象ではない (バックエンドでの事象) かと思いますが、
それらしきレポジトリが見当たらない && 関連した PR / Issue が見当たらなかったため申し訳無いですがここに報告させてください。

https://mstdn.owatan.jp/@owatan/102364179188141656
上記のトゥートのように、下記条件で Push 通知を新規に登録しようとすると
スクリーンショットのように `500` であろうレスポンスが帰ってきます。
(アカウント→認証済みアプリ から確認すると、これ用の CS/CK はきちんと発行されているように見えます。)

- iMast のバージョン: 3.2.2(166)
- iOS のバージョン: 12.3.1
- 端末名: iPhone11,2

個人鯖で利用していますが、ホストに入れたリバースプロキシのログや
Docker で利用している Mastodon の Web  サーバのログ (`live_web_1`) を見ても、明確にエラーだ！と推定できるようなものが見当たりませんでした (これを見ろ、などあれば教えてください 🙏 ) 。

2019/12/31 に現行のシステムの Push 通知はサービスを終了するようなので、無理せず余力があれば 🙏

**Comment by rinsuki** [comment]
報告ありがとうございます。
サーバー側のログを見たところ、Mastodonサーバー側にWebPush用の鍵がない場合に起こりそうなエラーのログがありました。
Mastodonサーバーの設定 (標準であれば `.env.production` ) に `VAPID_PRIVATE_KEY` / `VAPID_PUBLIC_KEY` が指定されているか、またWebUIでのプッシュ通知は利用できるかをご確認ください。

---

また、サーバー側のコードは諸般の都合によりGitHubのプライベートリポジトリで運用されており、私以外は Issue / Pull Requestの作成はできない状態になっています (GitHub にも GitLab のような Issueだけ公開するオプションがあればよいのですが…)。

**Comment by owatan** [comment]
ありがとうございます、設定しないといけない項目があったんですね ... (気づいてませんでした)
設定してからやってみたところ、無事に有効化することができました、ありがとうございました 🙏
