### ISSUE TITLE
フォローリクエストの項目を少ない手数で表示に。

### ISSUE THREAD

**Issue by mikage-961pro** [cinderella-project/iMast#167]
現在、フォローリクエストは、
その他＞自分のプロフィール＞右上の…＞フォローリクエストのところにある。

それを
その他＞フォローリクエストというように表示してほしい。

**Comment by rinsuki** [comment]
設定→実験的な要素→最初の画面を新しいものに(α) をオンにするとこういう画面になり、導線が短くなります。
<img src="https://user-images.githubusercontent.com/6533808/78463379-ded97300-7716-11ea-84db-2c4d01a4eb1f.png" height=360>

古い方の画面は呼び出せる機能を同等にする以外はなるべくメンテしない予定なので、まあ実装されたらいいかも…?ぐらいな感じで…。
