### ISSUE TITLE
iPad OSでスクショをあげようとすると容量オーバーとなりアップロードできない

### ISSUE THREAD

**Issue by mikage-961pro** [cinderella-project/iMast#174]
![IMG_0103](https://user-images.githubusercontent.com/50665049/82614489-f86d4600-9c02-11ea-8d8c-09b65af77a04.PNG)
スクリーンショットを撮ってiMast経由でアップロードするとエラーが発生してしまう。
## Steps to reproduce the problem
1. iMastの写真添付の場所をタップし画像選択
2. Tootを実施
3. 添付画像のエラー発生

## Observed behavior
写真Appで1pxでも編集入れるとアップロード可能になる

## Expected behaviour

WEBでも同じ現象が発生するため、iPadのスクショデータの問題かなと思うが、画像アップロード時に画像をコピペでトゥート欄にコピペするとアップロードは可能。なので、マストドンかスクショの写真の問題かと思われる。

環境：
iPad Pro 11inch iPad OS 13.5

**Comment by mikage-961pro** [comment]
マストドン側のメディアサイズ制限の変更(例えば8MB→20MB)すればiPad問題改善するご様子のためクローズ

**Comment by rinsuki** [comment]
投稿設定→画像の自動リサイズでリサイズ設定を入れればアップロード前に縮小処理が走るので成功するはずです
