### ISSUE TITLE
Googleフォトから画像を共有した時に、投稿に謎のURIが付加される

### ISSUE THREAD

**Issue by mlny** [cinderella-project/iMast#48]
# 症状
![20170915_110250](https://user-images.githubusercontent.com/5173607/30463516-22ead92a-9a07-11e7-8ed2-489c60256c85.png)

https://imastodon.net/@malony/3247531
https://imastodon.net/@malony/3247622

# 再現
1. [Googleフォト](https://itunes.apple.com/jp/app/google-%E3%83%95%E3%82%A9%E3%83%88-%E5%86%99%E7%9C%9F%E3%82%84%E5%8B%95%E7%94%BB%E3%82%92%E4%BF%9D%E7%AE%A1/id962194608?mt=8)アプリで画像を表示する
2. [↑]ボタンから画像を共有する
![img_1342](https://user-images.githubusercontent.com/5173607/30463579-7d98ddf4-9a07-11e7-925a-fd179a9eadd8.PNG)
![img_1343](https://user-images.githubusercontent.com/5173607/30463581-82486f54-9a07-11e7-891d-d09991b822a7.PNG)
![img_1344](https://user-images.githubusercontent.com/5173607/30463585-8841970a-9a07-11e7-8230-22fd7557f64d.PNG)

# 症状を確認した機種
* iPad(5th) @ iOS11.0 GM
* iPhone 6s @ iOS10.3.3

**Comment by Petitsurume** [comment]
修正しました。次のTestFlight砲で直ったものが降ってくるはずです。

<details>
<summary>技術的詳細(実質メモ)</summary>
GoogleDrive/GooglePhotoは共有時に

- `public.png`
- `public.file-url`

を共有しているようですが、このうち`public.png`は`public.image`に、`public.file-url`は`public.url`に格下げされます。

iMastはてっきり`public.url`には`https?://`しか降ってこないと思い込んでたのでこうなりました。

結果的には、URLを投稿に付与する段階でURLのスキーマが`file://`だったら弾く処理を追加して解決しました。

</details>
