### ISSUE TITLE
タイムラインのスワイプメニューからfavやBTをした時になんらかのレスポンスがほしい

### ISSUE THREAD

**Issue by mlny** [cinderella-project/iMast#93]
favやBTがうまくいったのか分からないのでなんらかの反応がほしい。トゥート詳細からのfavやBTだとボタン部分の色が変わるので分かるようになっているけど、スワイプメニューからだとわからない。

UIのイメージ  
**画像を削除しました。申し訳ございませんでした**

**Comment by rinsuki** [comment]
とりあえず、こんな感じでBT/favしたものには右端に印をつけるようにしてみましたが、どうでしょうか(TestFlightはまだ飛んでません)
![456ac1a1-50bf-43d8-ae13-e91e1f8318bd](https://user-images.githubusercontent.com/6533808/39947553-4a3a9922-55ad-11e8-8f62-d7bb486563d5.jpeg)

おまけ: そのアカウントは一応鍵垢で連合からのフォローも(一部箪笥除いて)弾いているアカウントなので、画像を差し替えていただけると助かります

**Comment by mlny** [comment]
良い感じです。ありがとうございます。画像は削除しました。

**Comment by rinsuki** [comment]
では https://github.com/cinderella-project/iMast/commit/33d63a326fa99e1b76ef033e052b6aa7649560ad で実装したので close します
